### ISSUE TITLE
Hash mismatch

### ISSUE THREAD

**Issue by matmarczak** [ChristophP/elm-i18next#36] opened 2022-02-01 10:34 UTC
Hi! Today I just started to get this error:
 ```Dependency problem!
-- CORRUPT PACKAGE DATA --------------------------------------------------------

I downloaded the source code for ChristophP/elm-i18next 4.0.0 from:

    https://github.com/ChristophP/elm-i18next/zipball/4.0.0/

But it looks like the hash of the archive has changed since publication:

  Expected: c520fd4838b17b6e258e02b0c8dca90f7445232b
    Actual: 46e0be50af207288b9bf621f350bca2f00b7701f

This usually means that the package author moved the version tag, so report it
to them and see if that is the issue. Folks on Elm slack can probably help as
well.
```
So just writing to you it happend :)

**Comment by ChristophP** [comment] 2022-02-02 08:39
Thanks @matmarczak ,
I saw some news on twitter that is is a bug caused by github deploying changes that resulted in package hashes to change. From what I got on twitter it seems they have rolled it back.
https://twitter.com/tgummerer/status/1488493440103030787
I will close this issue. Please reopen if this issue persists.

**Closed as completed by ChristophP** 2022-02-02 08:39 UTC
